modLoader="javafml"
loaderVersion="[36,)"
license="Apache License, Version 2.0"
issueTrackerURL="https://github.com/AnAwesomGuy/bosstools-performance"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="BossTools Performance"
authors="${mod_authors}"
logoFile="icon.png"
description='''Performance optimizations for extremely questionable Space-BossTools code'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="boss_tools"
mandatory=true
versionRange="[5.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="modernfix"
mandatory=true
versionRange="[5.7,)"
ordering="BEFORE"
side="BOTH"
